# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e347827eaef8a57cfaa0144e991ccb1ddd3d584b4e2f18ec71e69e1515cb0a3a06cce005da95615936fca5e7afa0f51301c98e53e4877de394a33baf845eceb

test:
  secret_key_base: 99e560610ca21bd99172eb36c418ede03df271dd32096ef3195cd41954d997ce6d7c32b6261af2e230378fd13dc9695ac944f87ea62cb5d7cda7e7c962182cc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
