# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


new_users = [
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'BillyBob', user_name: 'bob'},
	{name: 'John Ceh', user_name: 'John'},
	{name: 'Miguel Ocana', user_name: 'smegal'},
	{name: 'David Fuka', user_name: 'graveto'},
	{name: 'Jake danforth', user_name: 'Jake'},
	{name: 'Deen Core', user_name: 'deen'},
	{name: 'Seema guru', user_name: 'Seema'},
	{name: 'Jaya Chandlaka', user_name: 'Jaya'},
	{name: 'Rene Martinez', user_name: 'Rene'},
	{name: 'Carol Cordova', user_name: 'Carol'},
	{name: 'Cameron Hicks', user_name: 'Cameron'}
	]
new_users.each do |user|
	User.create(name: user[:name], user_name: user[:user_name])
end